nome: Gerar Dados

em:
  horário: # executar a cada 12 horas
    - cron: "* */12 * * * *
  workflow_dispatch:

empregos:
  construir:
    nome: Empregos para atualizar dados
    em funcionamento: ubuntu-mais recente
    passos:
      # Animação cobra
      - usos: Platane/snk@master
        id: snake-gif
        com:
          github_user_name: PedroHenri1606
          svg_out_path: dist/github-contribution-grid-snake.svg

      - usos: crazy-max/ghaction-github-pages@v2.1.3
        com:
          target_branch: saída
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ segredos. GITHUB_TOKEN }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
